// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cowbhjsnzplueyaxmwsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvd2JoanNuenBsdWV5YXhtd3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTUyNTYsImV4cCI6MjA3MTE5MTI1Nn0.zFA2XPVgGnLu6GXR6bnkEpdR4T4Jm-_mh2aiEsXfORI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});